import { useEffect, useRef, useState } from 'react';
import quickQuote from './assets/icons/quick-quote.png';
import quickCustomer from './assets/icons/quick-customer.png';
import quickProduct from './assets/icons/quick-product.png';
import quickFollow from './assets/icons/quick-follow.png';
import navHome from './assets/icons/nav-home.png';
import navTodo from './assets/icons/nav-todo.png';
import navProject from './assets/icons/nav-project.png';
import navProfile from './assets/icons/nav-profile.png';
import performanceShape from './assets/performance-card-shape.svg';
import performanceTitleIcon from './assets/performance-title-icon.svg';
import performancePlaneAccent from './assets/performance-plane-accent.svg';
import performancePlane from './assets/performance-plane.png';
import projectShowroom from './assets/project-showroom.png';
import projectIndustrialPark from './assets/project-industrial-park.png';
import featuredPanelShape from './assets/featured-panel-shape.svg';
import featuredHeaderGradient from './assets/featured-header-gradient.svg';

type IconName='quote'|'customer'|'product'|'follow'|'home'|'todo'|'project'|'me';
type Task={id:number;type:string;name:string;deadline:string;action:string};
type RequestState='idle'|'loading'|'success'|'error';
type Route='home'|'todo'|'project'|'customer'|'product'|'profile'|'filter'|'opportunities';
const icons:Record<IconName,string>={quote:quickQuote,customer:quickCustomer,product:quickProduct,follow:quickFollow,home:navHome,todo:navTodo,project:navProject,me:navProfile};
const seedTasks:Task[]=[{id:1,type:'报价确认',name:'南通电子厂报价',deadline:'今天 10:30 截止',action:'确认报价'},{id:2,type:'客户回访',name:'苏州门店项目',deadline:'今天 14:00 截止',action:'开始回访'},{id:3,type:'方案提交',name:'无锡食品厂方案',deadline:'明天 09:30 截止',action:'提交方案'}];
function Icon({name}:{name:IconName}){return <img src={icons[name]} alt="" aria-hidden="true"/>}
function StatusBar(){return <div className="status-bar"><strong>9:41</strong><div className="status-icons" aria-label="信号满格，Wi-Fi 已连接，电量充足"><svg viewBox="0 0 23 14"><rect x="1" y="9" width="3" height="4" rx="1"/><rect x="6" y="6" width="3" height="7" rx="1"/><rect x="11" y="3" width="3" height="10" rx="1"/><rect x="16" width="3" height="13" rx="1"/></svg><svg viewBox="0 0 18 14"><path d="M1 4c5-4 11-4 16 0M4 8c3-3 7-3 10 0m-7 3c1.4-1.2 2.6-1.2 4 0"/></svg><svg className="battery" viewBox="0 0 28 14"><rect x="1" y="1" width="23" height="12" rx="2"/><path d="M26 5v4"/><rect x="3" y="3" width="18" height="8" rx="1" fill="currentColor" stroke="none"/></svg></div></div>}

function useAnimatedValue(target:number,duration=500){const[value,setValue]=useState(target);const previous=useRef(target);useEffect(()=>{const from=previous.current;const started=performance.now();let frame=0;const tick=(now:number)=>{const t=Math.min(1,(now-started)/duration);const eased=1-Math.pow(1-t,3);setValue(from+(target-from)*eased);if(t<1)frame=requestAnimationFrame(tick);else previous.current=target};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[target,duration]);return value}
function SegmentedGauge({value}:{value:number}){const percent=Math.min(100,Math.max(0,value));const segments=72;return <div className="performance-gauge" aria-label={`完成率${percent.toFixed(1)}%`}><svg viewBox="0 0 88 88" role="img" aria-hidden="true"><defs><linearGradient id="gauge-progress" x1="8" y1="18" x2="80" y2="70" gradientUnits="userSpaceOnUse"><stop stopColor="#49D6E9"/><stop offset="1" stopColor="#73DCC8"/></linearGradient></defs>{Array.from({length:segments},(_,index)=>{const angle=135+(270*index)/(segments-1);const radians=angle*Math.PI/180;const active=index/(segments-1)<=percent/100;return <line key={index} x1={44+34*Math.cos(radians)} y1={44+34*Math.sin(radians)} x2={44+41*Math.cos(radians)} y2={44+41*Math.sin(radians)} className={active?'active':''}/>})}<circle cx="44" cy="44" r="31"/></svg><strong>{percent.toFixed(1).split('.')[0]}<small>.{percent.toFixed(1).split('.')[1]}%</small></strong><span className="gauge-zero">0%</span><span className="gauge-full">100%</span></div>}
function PerformanceCard({amount,quoteProgress}:{amount:number;quoteProgress:number}){const plan=100;const animatedAmount=useAnimatedValue(amount);const percent=Math.min(100,Math.max(0,animatedAmount/plan*100));const gap=Math.max(0,plan-animatedAmount);return <section className="performance-original" aria-label="当月业绩完成率"><img className="performance-shape" src={performanceShape} alt=""/><img className="performance-title-icon" src={performanceTitleIcon} alt=""/><h2>当月业绩完成率</h2><SegmentedGauge value={percent}/><div className="performance-sales"><div><span>实际销售额（万元）</span><strong>{animatedAmount.toFixed(1)}</strong></div><div><span>计划销售额（万元）</span><strong>{plan}</strong></div><p>{gap>0?`距目标还差 ${gap.toFixed(1)} 万元`:'本月目标已完成'}</p></div><div className="performance-plane"><img className="plane-accent" src={performancePlaneAccent} alt=""/><span><img src={performancePlane} alt="纸飞机与绿叶装饰"/></span></div><div className="performance-divider"/><div className="performance-stats">{[['意向客户','8/12'],['报价中',`${quoteProgress}/14`],['合同签约','15/20']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>}

function QuickActions({navigate,onCreate}:{navigate:(r:Route)=>void;onCreate:()=>void}){const list:{label:string;icon:IconName;run:()=>void}[]=[{label:'一键报价',icon:'quote',run:onCreate},{label:'客户管理',icon:'customer',run:()=>navigate('customer')},{label:'产品中心',icon:'product',run:()=>navigate('product')},{label:'项目跟进',icon:'follow',run:()=>navigate('project')}];return <section className="quick-actions">{list.map(x=><button key={x.label} onClick={x.run}><span className={`action-icon ${x.icon}`}><Icon name={x.icon}/></span><span>{x.label}</span></button>)}</section>}

function NextAction({task,state,onView,onConfirm,onUndo,onRetry}:{task:Task;state:RequestState;onView:()=>void;onConfirm:()=>void;onUndo:()=>void;onRetry:()=>void}){const viewLabel=task.id===1?'查看报价':task.id===2?'查看客户':'查看方案';return <section className={`next-v2 next-v3 ${state}`} aria-live="polite" aria-busy={state==='loading'}><div className="next-v3-copy"><h2>下一步行动</h2><strong>{state==='success'?`${task.type}已完成`:task.name}</strong><p><span>{task.type}</span>{state==='success'?'数据已同步':task.deadline}</p>{state==='error'&&<small role="alert">报价确认失败，请重试</small>}</div><div className="next-v3-actions">{state==='success'?<button className="undo-v2" onClick={onUndo}>已确认 · 撤销</button>:<><button className="secondary-v2" disabled={state==='loading'} onClick={onView}>{viewLabel}</button><button className="primary-v2" disabled={state==='loading'} onClick={state==='error'?onRetry:onConfirm}>{state==='loading'?<><span className="spinner"/>确认中…</>:state==='error'?'重试':task.action}</button></>}</div></section>}

function TaskList({tasks,onAll,onOpen}:{tasks:Task[];onAll:()=>void;onOpen:(t:Task)=>void}){return <section className="news-panel task-panel-v2"><header><h2><span>✓</span> 待办任务 <em>{tasks.length}</em></h2><button onClick={onAll}>查看全部 <b>›</b></button></header>{tasks.slice(0,3).map((t,i)=><button className="task-row-v2" key={t.id} onClick={()=>onOpen(t)}><span className="task-index">{i+1}</span><span className="task-content"><small>{t.type}</small><strong>{t.name}</strong><time>{t.deadline}</time></span><span className="task-direct">{t.action} ›</span></button>)}</section>}

function ProjectSection({updated,onView}:{updated:boolean;onView:(name:string)=>void}){const projects=[{name:'新东门店新风系统',image:projectShowroom,tags:['行程待确认','区域示范门店'],date:'2025年06月22日',owner:'孟晓灵',risk:updated?'低风险':'进度延迟2天'},{name:'海安智造园空气改造',image:projectIndustrialPark,tags:['重点跟进','方案评审中'],date:'2025年06月28日',owner:'周子涵',risk:'设备清单待确认'}];return <section className="featured-original"><img className="featured-original-shape" src={featuredPanelShape} alt=""/><header><img src={featuredHeaderGradient} alt=""/><h2>重点项目</h2></header><div className="featured-original-list">{projects.map(p=><button className="featured-original-card" key={p.name} onClick={()=>onView(p.name)}><img src={p.image} alt={`${p.name}项目图片`}/><span><strong>{p.name}</strong><span className="featured-original-tags">{p.tags.map(t=><i key={t}>{t}</i>)}</span><small>计划拜访时间：{p.date}</small><small>负责人：{p.owner}</small><small className="featured-original-risk">风险：{p.risk}</small></span></button>)}</div></section>}

function DemoControls({onReset,onFail}:{onReset:()=>void;onFail:()=>void}){return <div className="demo-controls" aria-label="演示数据控制"><button onClick={onReset}>重置演示数据</button><button onClick={onFail}>测试确认失败</button></div>}

function QuoteSheet({state,expanded,onClose,onConfirm,onExpand}:{state:RequestState;expanded:boolean;onClose:()=>void;onConfirm:()=>void;onExpand:()=>void}){return <div className="sheet-backdrop" onMouseDown={onClose}><section className="quote-sheet" role="dialog" aria-modal="true" aria-labelledby="quote-title" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><header><div><small>报价详情</small><h2 id="quote-title">南通电子厂新风系统报价</h2></div><button onClick={onClose} aria-label="关闭报价详情">×</button></header><div className="quote-summary"><dl><div><dt>客户名称</dt><dd>南通电子厂</dd></div><div><dt>报价编号</dt><dd>QT-20250618-032</dd></div><div><dt>总金额</dt><dd className="quote-total">¥50,000.00</dd></div><div><dt>有效期</dt><dd>2025年06月30日</dd></div><div><dt>负责人</dt><dd>小凌经理</dd></div><div><dt>付款方式</dt><dd>30%预付款，验收后付清</dd></div></dl></div><div className="quote-products"><h3>产品明细</h3><div className="product-head"><span>产品名称</span><span>数量</span><span>单价</span><span>小计</span></div><div className="product-line"><span>商用新风主机 X500</span><span>1台</span><span>¥40,000</span><span>¥40,000</span></div><div className="product-line"><span>智能控制面板 Pro</span><span>1套</span><span>¥5,000</span><span>¥5,000</span></div><div className="product-line"><span>安装及辅材服务</span><span>1项</span><span>¥5,000</span><span>¥5,000</span></div></div><div className="quote-note"><strong>备注</strong><p>包含运输、标准安装及首次调试；超出标准施工范围的费用另行确认。</p></div>{expanded&&<div className="expanded-quote" role="status">完整报价单已展开：含税金额 ¥50,000.00，质保期 24 个月。</div>}{state==='error'&&<p className="sheet-error" role="alert">报价确认失败，请重试</p>}<div className="sheet-actions"><button className="secondary-v2" onClick={onExpand}>{expanded?'收起完整报价单':'查看完整报价单'}</button><button className="primary-v2" disabled={state==='loading'} onClick={onConfirm}>{state==='loading'?<><span className="spinner"/>确认中…</>:'确认报价'}</button></div></section></div>}

function CreateQuoteSheet({onClose}:{onClose:()=>void}){return <div className="sheet-backdrop" onMouseDown={onClose}><section className="quote-sheet create-sheet" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><header><div><small>快速报价</small><h2>新建报价</h2></div><button onClick={onClose} aria-label="关闭">×</button></header><label>客户名称<input placeholder="选择或输入客户名称"/></label><label>报价产品<input placeholder="选择产品"/></label><label>数量<input type="number" defaultValue="1"/></label><button className="primary-v2 create-submit" onClick={onClose}>继续填写报价</button></section></div>}

function RoutePage({route,title,onBack}:{route:Route;title:string;onBack:()=>void}){const copy:Record<string,string>={todo:'全部待办已按优先级和截止时间排序',customer:'查看客户档案、联系人和最近跟进记录',product:'浏览产品、规格与最新报价',project:'查看全部项目阶段、风险和下一节点',profile:'个人设置与工作统计',filter:`已应用“${title}”状态筛选`,opportunities:'3 个高意向客户和 2 份待确认报价值得优先跟进'};return <main className="route-page"><header><button onClick={onBack}>‹ 返回</button><h1>{title}</h1></header><section><h2>{copy[route]}</h2><p>这是从工作台直接进入的业务页面，不使用提示弹窗。</p></section></main>}

function BottomNav({active,onChange}:{active:string;onChange:(name:string)=>void}){const items:{label:string;icon:IconName}[]=[{label:'工作台',icon:'home'},{label:'待办',icon:'todo'},{label:'项目',icon:'project'},{label:'我的',icon:'me'}];return <nav className="bottom-nav"><div className="nav-items">{items.map(x=><button key={x.label} className={active===x.label?'active':''} aria-current={active===x.label?'page':undefined} onClick={()=>onChange(x.label)}><span><Icon name={x.icon}/></span>{x.label}</button>)}</div><div className="home-indicator"/></nav>}

export default function App(){const[tasks,setTasks]=useState(seedTasks);const[actionTask,setActionTask]=useState(seedTasks[0]);const[state,setState]=useState<RequestState>('idle');const[amount,setAmount]=useState(72.5);const[quoteProgress,setQuoteProgress]=useState(12);const failNext=useRef(false);const[route,setRoute]=useState<Route>('home');const[routeTitle,setRouteTitle]=useState('');const[sheet,setSheet]=useState<'quote'|'create'|null>(null);const[expanded,setExpanded]=useState(false);const[projectUpdated,setProjectUpdated]=useState(false);const[projectLoading,setProjectLoading]=useState(false);const[toast,setToast]=useState('');const timer=useRef<number|null>(null);useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(''),4000);return()=>window.clearTimeout(id)},[toast]);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const navigate=(r:Route,title='')=>{setRoute(r);setRouteTitle(title);window.scrollTo({top:0,behavior:'smooth'})};
 const confirm=()=>{if(state==='loading')return;setState('loading');setTimeout(()=>{if(failNext.current){failNext.current=false;setState('error');setToast('报价确认失败，请重试');return}const remaining=tasks.filter(t=>t.id!==actionTask.id);setTasks(remaining);setActionTask(remaining[0]??seedTasks[0]);setAmount(v=>v+5);setQuoteProgress(v=>Math.min(14,v+1));setProjectUpdated(true);setState('idle');setSheet(null);setToast('报价已确认：5万元已计入业绩，待办与业绩已同步')},850)};
 const undo=()=>{if(timer.current)clearTimeout(timer.current);setTasks(list=>[...list,actionTask].sort((a,b)=>a.id-b.id));setAmount(v=>Math.max(72.5,v-5));setQuoteProgress(v=>Math.max(0,v-1));setProjectUpdated(false);setState('idle');setToast('已撤销报价确认，相关数据已恢复')};
 const resetDemo=()=>{if(timer.current)clearTimeout(timer.current);setTasks(seedTasks);setActionTask(seedTasks[0]);setAmount(72.5);setQuoteProgress(12);setProjectUpdated(false);failNext.current=false;setState('idle');setSheet(null);setToast('演示数据已重置')};
 const prepareFailure=()=>{resetDemo();failNext.current=true;setToast('失败场景已准备，下一次确认将失败')};
 const updateProject=()=>{setProjectLoading(true);setTimeout(()=>{setProjectLoading(false);setProjectUpdated(true);setToast('项目进度已更新')},700)};
 const nav=(name:string)=>{if(name==='工作台')navigate('home');else if(name==='待办')navigate('todo','待办中心');else if(name==='项目')navigate('project','项目中心');else navigate('profile','我的')};
 const active=route==='home'?'工作台':route==='todo'?'待办':route==='project'?'项目':route==='profile'?'我的':'';
 return <div className="app-shell">{route==='home'?<main className="home-main"><div className="hero hero-v2"><StatusBar/><div className="line-art"/><h1>早上好，小凌经理<small>今日有 <b>{tasks.length}</b> 项待处理</small></h1><PerformanceCard amount={amount} quoteProgress={quoteProgress}/></div><div className="content"><QuickActions navigate={navigate} onCreate={()=>setSheet('create')}/><NextAction task={actionTask} state={state} onView={()=>actionTask.id===1?setSheet('quote'):navigate('todo',actionTask.name)} onConfirm={confirm} onRetry={confirm} onUndo={undo}/><TaskList tasks={tasks} onAll={()=>navigate('todo','待办中心')} onOpen={t=>{setActionTask(t);t.id===1?setSheet('quote'):navigate('todo',t.name)}}/><ProjectSection updated={projectUpdated} onView={name=>navigate('project',name)}/><DemoControls onReset={resetDemo} onFail={prepareFailure}/></div></main>:<RoutePage route={route} title={routeTitle||'工作台'} onBack={()=>navigate('home')}/>}<BottomNav active={active} onChange={nav}/>{toast&&<div className="toast" role="status">{toast}</div>}{sheet==='quote'&&<QuoteSheet state={state} expanded={expanded} onClose={()=>{if(state!=='loading')setSheet(null)}} onConfirm={confirm} onExpand={()=>setExpanded(v=>!v)}/>} {sheet==='create'&&<CreateQuoteSheet onClose={()=>setSheet(null)}/>}</div>}
